ground-x/caver-java-ext-kas

- README.md
This PR add maven, gradle build settings in README.md file.
> add maven, gradle build settings.

- build.gradle
This PR introduces modify group id in build.gradle for uploading maven central
> modify group id in build.gradle

- settings.gradle
This PR modify project name 
- caver-java-kas-ext -> caver-java-ext-kas
> modify project name.

- .circleci/config.yml
- .circleci/scripts/release_tag_branch.sh
- Fix tagging error on major version
- Change publish logic test before deploy major version(same as rc publish)
> [CIRCLECI] fix tagging error / deploy logic major version

- TERMS-OF-USE.md
This PR modify KAS hompage url in TERMS_OF_USE.md
> modify KAS hompage url.

- TERMS-OF-USE.md
This PR introduces modification few words in terms of use file
> Modified terms of use file

- .circleci/config.yml
- Add test context when it test, it contains KAS credential, Klaytn address for baobab
> [CIRCLECI] add context for test job

- .gitignore
- README.md
- build.gradle
- src/test/java/xyz/groundx/caver_ext_kas/Config.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/anchor/AnchorAPITest.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/tokenhistory/TokenHistoryAPITest.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/wallet/WalletAPITest.java
- src/test/java/xyz/groundx/caver_ext_kas/node/NodeAPITest.java
This PR modify test environment.
- Set the Test data in variable way.
- set the data in Config.java
- Define System environment variable
- Define environment variable using .env
> modify test environment.

- javadocFormatting.sh
Add a shell script that performs the following functions.
- \&lt;p\&gt;\&lt;/p\&gt; -> \<p>\</p>
- \&lt;br\&gt; -> \<br>
> add javadoc formatting shall script

- find_version.py
This PR modify find_version.py script.
> modify find_version script

- README.md
- build.gradle
- src/test/java/xyz/groundx/caver_ext_kas/kas/tokenhistory/TokenHistoryAPITest.java
This PR update caver-java version.
> using latest caver-java version

- src/main/java/xyz/groundx/caver_ext_kas/exception/ExceptionDetail.java
- src/main/java/xyz/groundx/caver_ext_kas/exception/KASAPIException.java
- src/main/java/xyz/groundx/caver_ext_kas/wallet/KASWallet.java
- src/test/java/xyz/groundx/caver_ext_kas/exception/KASAPIExceptionTest.java
- src/test/java/xyz/groundx/caver_ext_kas/wallet/KASWalletTest.java
This PR added KASAPIException which wrapped ApiException class and apply code.
> add KASAPIException

- build.gradle
- src/main/java/xyz/groundx/caver_ext_kas/wallet/KASWallet.java
- src/test/java/xyz/groundx/caver_ext_kas/wallet/ContractSampleData.java
- src/test/java/xyz/groundx/caver_ext_kas/wallet/KASWalletIntegrationTest.java
This PR add KASWallet integration test.
- The AccountUpdate Transaction test was commented out due to an issue.
> add KASWallet integration test.

- README.md
- build.gradle
This PR follow the contents
- add KASWallet description in README.md 
- apply latest caver-java version
> add KASWallet description in README.md

- README.md
This PR add KASWallet contents(Introduced KASWallet) in table of contents
> add KASWallet contents in table of contents

- build.gradle
This PR updates caver-java version.
> update caver-java version

- build.gradle
This PR updates caver-java-ext-kas version.
> update version to 1.0.2

- codegen/config_anchor.json
- codegen/config_tokenHistory.json
- codegen/config_wallet.json
- codegen/generate_anchor.sh
- codegen/generate_tokenHistory.sh
- codegen/generate_wallet.sh
- src/test/java/xyz/groundx/caver_ext_kas/kas/tokenhistory/TokenHistoryAPITest.java
This PR add a shall script that generating rest-client code by using swagger-codegen with config.json.
> add shall script that generating rest-client code by using swagger-codegen.

- src/test/java/xyz/groundx/caver_ext_kas/Config.java
This PR add a following contents.
- add to env key specified KAS API URL in .env 
- add a initialize KIP-17 API code in Config.java
> add a KAS API URL in .env

- src/main/java/xyz/groundx/caver_ext_kas/kas/anchor/Anchor.java
- src/main/java/xyz/groundx/caver_ext_kas/kas/kip17/KIP17.java
- src/main/java/xyz/groundx/caver_ext_kas/kas/tokenhistory/TokenHistory.java
- src/main/java/xyz/groundx/caver_ext_kas/kas/wallet/Wallet.java
- src/main/java/xyz/groundx/caver_ext_kas/rest_client/io/swagger/client/ApiClient.java
This PR add a ApiClient object Getter / Setter function in Anchor, TokenHistory, Wallet, KIP17 class
- ApiClient can configure settings that can be used when executing each KAS API. Therefore, make ApiClient accessible to each API instance.
> add ApiClient setter

- src/test/java/xyz/groundx/caver_ext_kas/Config.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/anchor/AnchorAPITest.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/kip17/KIP17Test.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/tokenhistory/TokenHistoryAPITest.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/wallet/WalletAPITest.java
This PR enable newly added test.(except Token history API)
> Enable newly added test

- build.gradle
This PR update version to v1.1.0
> update version to v1.1.0

- src/main/java/xyz/groundx/caver_ext_kas/rest_client/io/swagger/client/api/kip17/api/Kip17Api.java
This pr apply add a newline tag for javadoc
> convert a newline formatting

- src/main/java/xyz/groundx/caver_ext_kas/kas/kip17/KIP17.java
- src/main/java/xyz/groundx/caver_ext_kas/kas/tokenhistory/TokenHistory.java
- src/main/java/xyz/groundx/caver_ext_kas/kas/wallet/Wallet.java
- src/test/java/xyz/groundx/caver_ext_kas/kas/wallet/WalletAPITest.java
This PR add code example in API description and enable test in Wallet class.
> add code example.

- build.gradle
This PR updated sdk version to v1.1.1
> Updated sdk version to v1.1.1

- TERMS-OF-USE.md
This PR introduces modification of company name
> Modified company name

- src/main/java/xyz/groundx/caver_ext_kas/kas/wallet/Wallet.java
This PR modify `registerAccounts()` code example
> modify registerAccounts() code example.

- src/main/java/xyz/groundx/caver_ext_kas/CaverExtKAS.java
This PR modify initKIP17API() function
> modify initKIP17API

- .github/CODEOWNERS
This PR added @aeharvlee as a code owner.
> Added code onwer

- build.gradle
This PR added a nexus staging info
> add a nexus staging info.

- src/main/java/xyz/groundx/caver_ext_kas/kas/wallet/Wallet.java
This PR suggests changing variable names.
I think the expressions below will be easier for SDK users to read and understand.
* `accounts` -> `accountsToBeMigrated`
* `migrationAccount` -> `accountToBeMigrated`
* `key` -> `newKey`
> Updated variable names used by Account Migration

- README.md
This PR added KIP-7 API in README.md.
> add KIP-7 API in readme.
